// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
case TargetPlatform.linux:
  return linux;  // Вместо throw UnsupportedError
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnrq6lPp_q8EcMhqpVvzM8LaTHbipgcnk',
    appId: '1:424132177009:web:e085773517f85cc7ad7fd0',
    messagingSenderId: '424132177009',
    projectId: 'telegraph-cbe5c',
    authDomain: 'telegraph-cbe5c.firebaseapp.com',
    storageBucket: 'telegraph-cbe5c.firebasestorage.app',
    measurementId: 'G-HW9EG5LWEC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaI22WATZGhPhjGE3RxYARqa655gaPEoU',
    appId: '1:424132177009:android:954dc72a3d0d7355ad7fd0',
    messagingSenderId: '424132177009',
    projectId: 'telegraph-cbe5c',
    storageBucket: 'telegraph-cbe5c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBm4tuhxqwbUonZvQ4TnIsQK-pAxSz8zpc',
    appId: '1:424132177009:ios:309799d692df484cad7fd0',
    messagingSenderId: '424132177009',
    projectId: 'telegraph-cbe5c',
    storageBucket: 'telegraph-cbe5c.firebasestorage.app',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBm4tuhxqwbUonZvQ4TnIsQK-pAxSz8zpc',
    appId: '1:424132177009:ios:309799d692df484cad7fd0',
    messagingSenderId: '424132177009',
    projectId: 'telegraph-cbe5c',
    storageBucket: 'telegraph-cbe5c.firebasestorage.app',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnrq6lPp_q8EcMhqpVvzM8LaTHbipgcnk',
    appId: '1:424132177009:web:cc6e453856db9a1cad7fd0',
    messagingSenderId: '424132177009',
    projectId: 'telegraph-cbe5c',
    authDomain: 'telegraph-cbe5c.firebaseapp.com',
    storageBucket: 'telegraph-cbe5c.firebasestorage.app',
    measurementId: 'G-G1VEYB7TT7',
  );
  // Добавь это в конец файла, после windows:
static const FirebaseOptions linux = FirebaseOptions(
  apiKey: 'AIzaSyCnrq6lPp_q8EcMhqpVvzM8LaTHbipgcnk',  // Берем из web
  appId: '1:424132177009:web:e085773517f85cc7ad7fd0',  // Web app ID
  messagingSenderId: '424132177009',
  projectId: 'telegraph-cbe5c',
  authDomain: 'telegraph-cbe5c.firebaseapp.com',
  storageBucket: 'telegraph-cbe5c.firebasestorage.app',
);
}
